# Imagen base oficial de Node
FROM node:20-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del proyecto
COPY . .

# Exponer el puerto que Vite usará
EXPOSE 5173

# Comando para iniciar el servicio en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
