version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
    restart: unless-stopped 

  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./backend/documentos/data:/data
    restart: unless-stopped 

  autenticacion:
    build: ./backend/autenticacion
    ports:
      - "8000:8000"
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      - rabbitmq
      - minio

  ciudadanos:
    build: ./backend/ciudadanos
    ports:
      - "8001:8001"
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      - autenticacion

  documentos:
    build: ./backend/documentos
    ports:
      - "8002:8002"
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
      - CITIZEN_MS_URL=http://ciudadanos:8001
    depends_on:
      - ciudadanos

  interoperabilidad:
    build:
      context: ./backend/interoperabilidad
    depends_on:
      rabbitmq:
        condition: service_healthy
      ciudadanos:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - RABBIT_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
      - CITIZEN_MS_URL=http://ciudadanos:8001
      - AUTH_MS_URL=http://autenticacion:8000
      - DOCUMENT_MS_URL=http://documentos:8002
    ports:
      - "8004:8000"  
    restart: unless-stopped

  listener_worker:
    build:
      context: ./backend/listener_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      ciudadanos:
        condition: service_started
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
    restart: unless-stopped

  notificaciones:
      build: ./backend/notificaciones
      container_name: notificaciones
      ports:
        - "8003:8003"
      env_file:
        - ./backend/notificaciones/.env
      depends_on:
        - rabbitmq

volumes:
  rabbitmq-data:

networks:
  default:
    driver: bridge
