services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # UI Management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  interoperabilidad:
    build:
      context: ./interoperabilidad
    container_name: interoperabilidad
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq/

  listener_worker:
    build:
      context: ./listener_worker
    container_name: listener_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq/

volumes:
  rabbitmq-data:

networks:
  default:
    driver: bridge
