import os
from dotenv import load_dotenv

load_dotenv()

GOVCARPETA_BASE_URL = os.getenv("GOVCARPETA_BASE_URL")
GOVCARPETA_OPERATOR_ID = os.getenv("GOVCARPETA_OPERATOR_ID")
GOVCARPETA_OPERATOR_NAME = os.getenv("GOVCARPETA_OPERATOR_NAME")
CIVITECH_BASE_URL = os.getenv("CIVITECH_BASE_URL")
RABBIT_URL = os.getenv("RABBIT_URL")
NOTIFY_QUEUE = os.getenv("NOTIFY_QUEUE")